# -*- coding: utf-8 -*-
"""Лаб_работа_6_Титов_ДС.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cD5X2lQsynatkYk7257ehyIA3squ6ZhU
"""

class UserAccount():

  def __init__(self,username,email,password):
    self.username = username
    self.email = email
    self.__password = password

  def get_password(self):
    return self.__password

  def set_password(self,new_password):
    self.__password = new_password

  def check_password(self,password):
    if password == self.__password:
      return True
    return False

acc_1 = UserAccount('admin','example@mail.ru','1234')

ch = int(input('1 - изменение пароля \n2 - проверка введененного пароля на корректность \n'))
if ch == 1:
  new_password = input('Новый пароль: ')
  acc_1.set_password(new_password)
  print(acc_1.get_password())
elif ch == 2:
  password = input('Введите пароль: ')
  print(acc_1.check_password(password))

class Vehicle():

  def __init__(self,make,model):
    self.make = make
    self.model = model

  def get_info(self):
    print(f'Марка: {self.make} \nМодель: {self.model}')

class Car(Vehicle):

  def __init__(self,make,model,fuel_type):
    super().__init__(make,model)
    self.fuel_type = fuel_type

  def get_info(self):
    super().get_info()
    print(f'{self.fuel_type}')

VAZ_2109 = Car('ВАЗ','2109',92)
jupiter = Vehicle('ИЖ','Юпитер')

jupiter.get_info()
VAZ_2109.get_info()