# -*- coding: utf-8 -*-
"""лаба3Титов.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IMdEkphbBV-O0AALyBzjhsOCDp6nDgPN
"""

#Титов Дмитрий, Лаб. работа №3, задание 1
def file_read(a):
  if a == 1:
    with open('example.txt','r') as file:
      content = file.read()
      print(content)
  elif a == 2:
    content = []
    with open('example.txt','r') as file:
      for line in file:
        content.append(line)
      line_choose = int(input('Номер строки, которую надо вывести '))
      print(content[line_choose-1])

a = int(input('1 - чтение всего файла\n2 - построчное чтение\n'))
file_read(a)

#Титов Дмитрий, Лаб. работа №3, задание 2
delete = int(input('1 - очистить файл\n2 - добавить текст\n'))
if delete == 1:
  with open('user_input.txt','w') as file:
    file.close()
else:
  a = input('Введите текст ')
  with open('user_input.txt','a+') as file:
    file.write(a)
    file.seek(0)
    content = file.read()
    print(content)

#Титов Дмитрий, Лаб. работа №3, задание 3
def file_read(a):
  try:
    if a == 1:
      with open('NOTexample.txt','r') as file:
        content = file.read()
        print(content)
    elif a == 2:
      content = []
      with open('NOTexample.txt','r') as file:
        for line in file:
          content.append(line)
        line_choose = int(input('Номер строки, которую надо вывести '))
        print(content[line_choose-1])
  except FileNotFoundError:
    print('Файл не найден!')

a = int(input('1 - чтение всего файла\n2 - построчное чтение\n'))
file_read(a)