# -*- coding: utf-8 -*-
"""Лаб_работа_5_Титов.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vfQfS7D27OglhgGbAoVPKYQ8915zM3jy
"""

#Титов Дмитрий Сергеевич, лаб. работа № 5, задание 1
class Book():
  def __init__(self,title,author,year):
    self.title = title
    self.author = author
    self.year = year

  def get_info(self):
    print(f'Название книги: {self.title}, Автор: {self.author}, Год издания: {self.year}')

book_1 = Book('Война и мир','Л.Н.Толстой','1868')

book_1.get_info()

#Титов Дмитрий Сергеевич, лаб. работа № 5, задание 2
class Circle():
  def __init__(self,radius):
    self.radius = radius

  def get_radius(self):
    return self.radius

  def set_radius(self,new_radius):
     self.radius = new_radius
     return self.radius

circle_1 = Circle(10)

change_radius = int(input('Новый радиус: '))
print(f'Изначальный радиус: {circle_1.get_radius()}')
print(f'Новый радиус: {circle_1.set_radius(change_radius)}')