# -*- coding: utf-8 -*-
"""Лаб_работа_4_Титов.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Moth2hnyoHxENdwpChIPHbMk0Xvn1mOz
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/sol2033/uni_labs.git
# %cd /content/uni_labs

#Титов Дмитрий Сергеевич. Лаб. работа 4, задание 1
import math
import datetime
a = int(input())
print(math.sqrt(a),datetime.datetime.now(),sep='\n')

#Титов Дмитрий Сергеевич. Лаб. работа 4, задание 2
import my_module
a = int(input())
b = int(input())
print(my_module.summ(a,b))

#Титов Дмитрий Сергеевич. Лаб. работа 4, задание 2
import package as pac
choice = 'умножение'
choice = int(input('1 - умножение чисел\n2 - сложение строк\n3 - определение простого числа\n '))
if choice == 1:
  a = int(input())
  b = int(input())
  print(pac.multi.multi(a,b))
elif choice == 2:
  a = input()
  b = input()
  print(pac.stringsum.stringsum(a,b))
elif choice == 3:
  a = int(input())
  print(pac.prime.prime(a))