# -*- coding: utf-8 -*-
"""Лаб_работа_7_Титов_ДС.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jdowAFeEIM1YZbO1q_NkkLSVLIi_r8QE
"""

class Employee():

  def __init__(self,name,id):
    self._name = name
    self._id = id

  def get_info(self):
    print(f'Имя: {self._name}\nID: {self._id} ')

class Manager(Employee):

  def __init__(self,name,id,department):
    super().__init__(name,id)
    self.department = department

  def manage_project(self):
    print(f'{self._name} управляет проектом')

  def get_info(self):
    super().get_info()
    print(f'отдел: {self.department}')

class Technician(Employee):

  def __init__(self,name,id,department,specialisation,grade):
    super().__init__(name,id)
    self.department = department
    self.specialisation = specialisation
    self._grade = grade

  def perform_maintance(self):
    print(f'{self.specialisation} {self._name} разряда {self._grade} выполняет тех. обслуживание объекта')

  def get_info(self):
    super().get_info()
    print(f'отдел: {self.department}\nспециальность: {self.specialisation}\nразряд: {self._grade} ')

class TechManager(Technician,Manager):
  def __init__(self,name,id,department,specialisation,grade):
    self._name = name
    self._id = id
    self.department = department
    self.specialisation = specialisation
    self._grade = grade

  def add_employee(self,emp_list):
    return emp_list.append(input('Добавить сотрудника: '))

  def get_team_info(self,emp_list):
    for i in emp_list:
      print(i)

manager_1 = Manager('Vladimir','1234','IT')
technician_1 = Technician('Sergey','4321','Marketing','engineer','2')
techmanager_1 = TechManager('Bob','5431','IT','senior engineer','1')

emp_list = ['Manager Vladimir','Technician Sergey','TechManager Bob']
ch = int(input('1 - менеджер\n2 - техник\n3 - менеджер-техник\n'))
if ch == 1:
  ch_m = int(input(' 1 - вывод информации о сотруднике\n 2 - управление проектом\n'))
  if ch_m == 1:
    manager_1.get_info()
  elif ch_m == 2:
    manager_1.manage_project()
elif ch == 2:
  ch_t = int(input(' 1 - вывод информации о сотруднике\n 2 - проведение тех. обслуживания\n'))
  if ch_t == 1:
    technician_1.get_info()
  elif ch_t == 2:
    technician_1.perform_maintance()
elif ch == 3:
  ch_tm = int(input(' 1 - вывод информации о сотруднике\n 2 - проведение тех. обслуживания\n 3 - управление проектом\n 4 - добавить нового сотрудника и вывести список всех сотрудников\n'))
  if ch_tm == 1:
    techmanager_1.get_info()
  if ch_tm == 2:
    techmanager_1.perform_maintance()
  if ch_tm == 3:
    techmanager_1.manage_project()
  if ch_tm == 4:
    techmanager_1.add_employee(emp_list)
    techmanager_1.get_team_info(emp_list)